.pyで出力
kbttik/readable_code_sample pull request #9
Opened 2021-04-03 02:21 UTC by Xapyha

2021-04-12 01:32 UTC, Xapyha commented
Please review my code!

2021-04-12 04:26 UTC, kbttik requested changes

2021-04-12 04:26 UTC, kbttik commented on chapter8/black/shiritori.py
> +        w1 = len(words[0]) #1つ前に格納したword
これで一つ前、2つ前取れないかもです。(2回目の入力 words[1]が1つ前、3回目の入力 word[2]が1つ前)

2021-04-12 04:26 UTC, kbttik commented on chapter8/black/shiritori.py
> +        if not jadge or word == "quit": #quitを入力してもis_not_match_headで判定される？>>Falseを返しているだけ
最初に引っかかったルール違反で返しますが、一度に他のルール違反も返さないと何回もやり直させてしまうかも

2021-04-12 04:26 UTC, kbttik commented on chapter8/black/shiritori.py
> +    print(word[-1])
debug素晴らし！けど、あげるときは消して(コメントアウト)からの方が良いかも！

2021-04-12 04:30 UTC, KaitoKk commented
レビューしてもらえる状態になったらwipを外してください

2021-04-17 09:38 UTC, Xapyha reviewed
レビューお願いします

2021-04-17 09:45 UTC, Xapyha commented on chapter8/black/shiritori.py
> +        if not jadge or word == "quit": #quitを入力してもis_not_match_headで判定される？>>Falseを返しているだけ
ルール違反の判定を統合しました．
確認お願いします

2021-04-24 01:26 UTC, merged